### ISSUE TITLE
Requirements could not deploy on Python3.10 

### ISSUE THREAD

**Issue by raviseerapu** [iterative/course-ds-base#40]
@Team, 
Trying to deploy requirements on Python3.10 version. Please let us know, is this specific specific python version have to deploy and test myself this code.

(dvc-venv) PS C:\Jan5-2021\DVC\course-ds-base> pip install -r .\requirements.txt
Collecting dvc==2.8.3
  Downloading dvc-2.8.3-py3-none-any.whl (399 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 399.3/399.3 kB 2.3 MB/s eta 0:00:00
Collecting joblib==1.0.1
  Downloading joblib-1.0.1-py3-none-any.whl (303 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 303.1/303.1 kB 6.2 MB/s eta 0:00:00
Collecting jupyter==1.0.0
  Using cached jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Collecting jupyter_contrib_nbextensions==0.5.1
  Downloading jupyter_contrib_nbextensions-0.5.1-py2.py3-none-any.whl (20.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 1.3 MB/s eta 0:00:00
Collecting matplotlib==3.4.3
  Downloading matplotlib-3.4.3.tar.gz (37.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.9/37.9 MB 1.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy==1.21.2
  Downloading numpy-1.21.2.zip (10.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 1.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pandas==1.3.2
  Downloading pandas-1.3.2.tar.gz (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 4.6 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [297 lines of output]
      Ignoring numpy: markers 'python_version == "3.7" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_machine != "aarch64
"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_machine != "aarch64
"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_machine == "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment    
      Ignoring numpy: markers 'python_version == "3.9" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment    
      Collecting setuptools>=51.0.0
        Using cached setuptools-65.5.0-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting Cython<3,>=0.29.21
        Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
      Collecting numpy==1.19.3
        Downloading numpy-1.19.3.zip (7.3 MB)
           ---------------------------------------- 7.3/7.3 MB 485.5 kB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
     
        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1
     
        [259 lines of output]
        setup.py:67: RuntimeWarning: NumPy 1.19.3 may not yet support Python 3.10.
          warnings.warn(
        Running from numpy source directory.
        setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
          run_build = parse_setuppy_commands()
        Processing numpy/random\_bounded_integers.pxd.in
        Processing numpy/random\bit_generator.pyx
        Processing numpy/random\mtrand.pyx
        Processing numpy/random\_bounded_integers.pyx.in
        Processing numpy/random\_common.pyx
        Processing numpy/random\_generator.pyx
        Processing numpy/random\_mt19937.pyx
        Processing numpy/random\_pcg64.pyx
        Processing numpy/random\_philox.pyx
        Processing numpy/random\_sfc64.pyx
        Cythonizing sources
        blas_opt_info:
        blas_mkl_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries mkl_rt not found in ['C:\\Jan5-2021\\DVC\\course-ds-base\\dvc-venv\\lib', 'C:\\']
          NOT AVAILABLE
     
        blis_info:
          libraries blis not found in ['C:\\Jan5-2021\\DVC\\course-ds-base\\dvc-venv\\lib', 'C:\\']
          NOT AVAILABLE
     
        openblas_info:
          libraries openblas not found in ['C:\\Jan5-2021\\DVC\\course-ds-base\\dvc-venv\\lib', 'C:\\']
        get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'      
        customize GnuFCompiler
        Could not locate executable g77
        Could not locate executable f77
        customize IntelVisualFCompiler
        Could not locate executable ifort
        Could not locate executable ifl
        customize AbsoftFCompiler
        Could not locate executable f90
        customize CompaqVisualFCompiler
        Could not locate executable DF
        customize IntelItaniumVisualFCompiler
        Could not locate executable efl
        customize Gnu95FCompiler
        Could not locate executable gfortran
        Could not locate executable f95
        customize G95FCompiler
        Could not locate executable g95
        customize IntelEM64VisualFCompiler
        customize IntelEM64TFCompiler
        Could not locate executable efort
        Could not locate executable efc
        customize PGroupFlangCompiler
        Could not locate executable flang
        don't know how to compile Fortran code on platform 'nt'
          NOT AVAILABLE
     
        atlas_3_10_blas_threads_info:
        Setting PTATLAS=ATLAS
          libraries tatlas not found in ['C:\\Jan5-2021\\DVC\\course-ds-base\\dvc-venv\\lib', 'C:\\']
          NOT AVAILABLE
     
        atlas_3_10_blas_info:
          libraries satlas not found in ['C:\\Jan5-2021\\DVC\\course-ds-base\\dvc-venv\\lib', 'C:\\']
          NOT AVAILABLE
     
        atlas_blas_threads_info:
        Setting PTATLAS=ATLAS
          libraries ptf77blas,ptcblas,atlas not found in ['C:\\Jan5-2021\\DVC\\course-ds-base\\dvc-venv\\lib', 'C:\\']
          NOT AVAILABLE
     
        atlas_blas_info:
          libraries f77blas,cblas,atlas not found in ['C:\\Jan5-2021\\DVC\\course-ds-base\\dvc-venv\\lib', 'C:\\']
          NOT AVAILABLE
     
        accelerate_info:
          NOT AVAILABLE
     
        C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\system_info.py:1914: UserWarning
:
            Optimized (vendor) Blas libraries are not found.
            Falls back to netlib Blas library which has worse performance.
            A better performance should be easily gained by switching
            Blas library.
          if self._calc_info(blas):
        blas_info:
          libraries blas not found in ['C:\\Jan5-2021\\DVC\\course-ds-base\\dvc-venv\\lib', 'C:\\']
          NOT AVAILABLE
     
        C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\system_info.py:1914: UserWarning
:
            Blas (http://www.netlib.org/blas/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [blas]) or by setting
            the BLAS environment variable.
          if self._calc_info(blas):
        blas_src_info:
          NOT AVAILABLE
     
        C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\system_info.py:1914: UserWarning
:
            Blas (http://www.netlib.org/blas/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [blas_src]) or by setting
            the BLAS_SRC environment variable.
          if self._calc_info(blas):
          NOT AVAILABLE
     
        non-existing path in 'numpy\\distutils': 'site.cfg'
        lapack_opt_info:
        lapack_mkl_info:
          libraries mkl_rt not found in ['C:\\Jan5-2021\\DVC\\course-ds-base\\dvc-venv\\lib', 'C:\\']
          NOT AVAILABLE
     
        openblas_lapack_info:
          libraries openblas not found in ['C:\\Jan5-2021\\DVC\\course-ds-base\\dvc-venv\\lib', 'C:\\']
          NOT AVAILABLE
     
        openblas_clapack_info:
          libraries openblas,lapack not found in ['C:\\Jan5-2021\\DVC\\course-ds-base\\dvc-venv\\lib', 'C:\\']
          NOT AVAILABLE
     
        flame_info:
          libraries flame not found in ['C:\\Jan5-2021\\DVC\\course-ds-base\\dvc-venv\\lib', 'C:\\']
          NOT AVAILABLE
     
        atlas_3_10_threads_info:
        Setting PTATLAS=ATLAS
          libraries lapack_atlas not found in C:\Jan5-2021\DVC\course-ds-base\dvc-venv\lib
          libraries tatlas,tatlas not found in C:\Jan5-2021\DVC\course-ds-base\dvc-venv\lib
          libraries lapack_atlas not found in C:\
          libraries tatlas,tatlas not found in C:\
        <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
          NOT AVAILABLE
     
        atlas_3_10_info:
          libraries lapack_atlas not found in C:\Jan5-2021\DVC\course-ds-base\dvc-venv\lib
          libraries satlas,satlas not found in C:\Jan5-2021\DVC\course-ds-base\dvc-venv\lib
          libraries lapack_atlas not found in C:\
          libraries satlas,satlas not found in C:\
        <class 'numpy.distutils.system_info.atlas_3_10_info'>
          NOT AVAILABLE
     
        atlas_threads_info:
        Setting PTATLAS=ATLAS
          libraries lapack_atlas not found in C:\Jan5-2021\DVC\course-ds-base\dvc-venv\lib
          libraries ptf77blas,ptcblas,atlas not found in C:\Jan5-2021\DVC\course-ds-base\dvc-venv\lib
          libraries lapack_atlas not found in C:\
          libraries ptf77blas,ptcblas,atlas not found in C:\
        <class 'numpy.distutils.system_info.atlas_threads_info'>
          NOT AVAILABLE
     
        atlas_info:
          libraries lapack_atlas not found in C:\Jan5-2021\DVC\course-ds-base\dvc-venv\lib
          libraries f77blas,cblas,atlas not found in C:\Jan5-2021\DVC\course-ds-base\dvc-venv\lib
          libraries lapack_atlas not found in C:\
          libraries f77blas,cblas,atlas not found in C:\
        <class 'numpy.distutils.system_info.atlas_info'>
          NOT AVAILABLE
     
        lapack_info:
          libraries lapack not found in ['C:\\Jan5-2021\\DVC\\course-ds-base\\dvc-venv\\lib', 'C:\\']
          NOT AVAILABLE
     
        C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\system_info.py:1748: UserWarning
:
            Lapack (http://www.netlib.org/lapack/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [lapack]) or by setting
            the LAPACK environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
        lapack_src_info:
          NOT AVAILABLE
     
        C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\system_info.py:1748: UserWarning
:
            Lapack (http://www.netlib.org/lapack/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [lapack_src]) or by setting
            the LAPACK_SRC environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
          NOT AVAILABLE
     
        numpy_linalg_lapack_lite:
          FOUND:
            language = c
            define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]
     
        C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\_distutils\dist.py:275: UserWarning: Unknown dis
tribution option: 'define_macros'
          warnings.warn(msg)
        running dist_info
        running build_src
        build_src
        building py_modules sources
        creating build
        creating build\src.win-amd64-3.10
        creating build\src.win-amd64-3.10\numpy
        creating build\src.win-amd64-3.10\numpy\distutils
        building library "npymath" sources
        Traceback (most recent call last):
          File "C:\Jan5-2021\DVC\course-ds-base\dvc-venv\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
            main()
          File "C:\Jan5-2021\DVC\course-ds-base\dvc-venv\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "C:\Jan5-2021\DVC\course-ds-base\dvc-venv\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 152, in prepare_metadata_
for_build_wheel
            return hook(metadata_directory, config_settings)
          File "C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\build_meta.py", line 157, in prepare_met
adata_for_build_wheel
            self.run_setup()
          File "C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\build_meta.py", line 248, in run_setup  
            super(_BuildMetaLegacyBackend,
          File "C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup  
            exec(compile(code, __file__, 'exec'), locals())
          File "setup.py", line 508, in <module>
            setup_package()
          File "setup.py", line 500, in setup_package
            setup(**metadata)
          File "C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\core.py", line 169, in s
etup
            return old_setup(**new_attr)
          File "C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\__init__.py", line 165, in setup        
            return distutils.core.setup(**attrs)
          File "C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup 
            dist.run_commands()
          File "C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_co
mmands
            self.run_command(cmd)
          File "C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_co
mmand
            cmd_obj.run()
          File "C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\command\dist_info.py", line 31, in run  
            egg_info.run()
          File "C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\command\egg_info.py", li
ne 24, in run
            self.run_command("build_src")
          File "C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_com
mand
            self.distribution.run_command(command)
          File "C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_co
mmand
            cmd_obj.run()
          File "C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\command\build_src.py", l
ine 144, in run
            self.build_sources()
          File "C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\command\build_src.py", l
ine 155, in build_sources
            self.build_library_sources(*libname_info)
          File "C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\command\build_src.py", l
ine 288, in build_library_sources
            sources = self.generate_sources(sources, (lib_name, build_info))
          File "C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\command\build_src.py", l
ine 378, in generate_sources
            source = func(extension, build_dir)
          File "numpy\core\setup.py", line 658, in get_mathlib_info
            st = config_cmd.try_link('int main(void) { return 0;}')
          File "C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 243,
 in try_link
            self._link(body, headers, include_dirs,
          File "C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\command\config.py", line
 162, in _link
            return self._wrap_method(old_config._link, lang,
          File "C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\command\config.py", line
 96, in _wrap_method
            ret = mth(*((self,)+args))
          File "C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 137,
 in _link
            (src, obj) = self._compile(body, headers, include_dirs, lang)
          File "C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\command\config.py", line
 105, in _compile
            src, obj = self._wrap_method(old_config._compile, lang,
          File "C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\command\config.py", line
 96, in _wrap_method
            ret = mth(*((self,)+args))
          File "C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 132,
 in _compile
            self.compiler.compile([src], include_dirs=include_dirs)
          File "C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 401, 
in compile
            self.spawn(args)
          File "C:\Users\seerapu\AppData\Local\Temp\pip-build-env-r0sar12d\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 505, 
in spawn
            return super().spawn(cmd, env=env)
          File "C:\Users\seerapu\AppData\Local\Temp\pip-install-jsn8okah\numpy_c87dffe387db45458072f04c8df762c4\numpy\distutils\ccompiler.py", line 90, 
in <lambda>
            m = lambda self, *args, **kw: func(self, *args, **kw)
        TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'
        [end of output]
     
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
     
      Encountered error while generating package metadata.
     
      See above for output.
     
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by raviseerapu** [comment]
Our current version of Python 3.10.0. Hence i changed some requirement.txt and updated accordingly. We will post if we find any issues..

dvc==2.8.3
joblib==1.0.1
jupyter==1.0.0
jupyter_contrib_nbextensions==0.5.1
matplotlib==3.6.1
numpy==1.23.4
pandas==1.5.1
pytest==6.2.4
python-box==5.4.1
pyyaml==5.4.1
scikit-learn==0.24.2
scipy==1.9.3
tqdm==4.64.1

**Comment by raviseerapu** [comment]
Installing collected packages: webencodings, wcwidth, voluptuous, text-unidecode, Send2Trash, pywin32, pytz, python-fsutil, pygtrie, pyasn1, pure-eval, 
ply, pickleshare, phonenumbers, nanotime, mistune, mailchecker, jupyter-highlight-selected-word, ipython-genutils, iniconfig, funcy, fastjsonschema, exe
cuting, dictdiffer, commonmark, backcall, appdirs, zc.lockfile, xmltodict, widgetsnbextension, websocket-client, urllib3, typing-extensions, traitlets, 
tornado, toml, tinycss2, threadpoolctl, tabulate, soupsieve, sniffio, smmap, six, shtab, shortuuid, ruamel.yaml.clib, pyzmq, pyyaml, pywinpty, python-sl
ugify, python-box, pyrsistent, pyparsing, pygments, pycparser, py, psutil, prompt-toolkit, prometheus-client, pluggy, pillow, pathspec, parso, pandocfil
ters, numpy, networkx, nest-asyncio, multidict, markupsafe, lxml, kiwisolver, jupyterlab-widgets, jupyterlab-pygments, joblib, idna, future, ftfy, fsspe
c, frozenlist, fonttools, entrypoints, dpath, distro, diskcache, defusedxml, decorator, debugpy, cycler, colorama, charset-normalizer, certifi, attrs, a
tpublic, atomicwrites, async-timeout, yarl, tqdm, terminado, scipy, ruamel.yaml, rich, requests, python-dateutil, pydot, packaging, matplotlib-inline, j
upyter-core, jsonschema, jinja2, jedi, grandalf, gitdb, flufl.lock, flatten-dict, dulwich, contourpy, configobj, cffi, bleach, beautifulsoup4, asttokens
, anyio, aiosignal, stack-data, scikit-learn, qtpy, python-benedict, pytest, pygit2, pandas, nbformat, matplotlib, jupyter-client, gitpython, argon2-cff
i-bindings, aiohttp, nbclient, ipython, argon2-cffi, aiohttp-retry, nbconvert, ipykernel, dvc, qtconsole, jupyter-server, jupyter-console, ipywidgets, n
otebook-shim, nbclassic, notebook, jupyter-latex-envs, jupyter-contrib-core, jupyter, jupyter-nbextensions-configurator, jupyter_contrib_nbextensions   
Successfully installed Send2Trash-1.8.0 aiohttp-3.8.3 aiohttp-retry-2.8.3 aiosignal-1.2.0 anyio-3.6.2 appdirs-1.4.4 argon2-cffi-21.3.0 argon2-cffi-bindi
ngs-21.2.0 asttokens-2.0.8 async-timeout-4.0.2 atomicwrites-1.4.1 atpublic-3.1.1 attrs-22.1.0 backcall-0.2.0 beautifulsoup4-4.11.1 bleach-5.0.1 certifi-
2022.9.24 cffi-1.15.1 charset-normalizer-2.1.1 colorama-0.4.5 commonmark-0.9.1 configobj-5.0.6 contourpy-1.0.5 cycler-0.11.0 debugpy-1.6.3 decorator-5.1
.1 defusedxml-0.7.1 dictdiffer-0.9.0 diskcache-5.4.0 distro-1.8.0 dpath-2.0.6 dulwich-0.20.46 dvc-2.8.3 entrypoints-0.4 executing-1.1.1 fastjsonschema-2
.16.2 flatten-dict-0.4.2 flufl.lock-7.1.1 fonttools-4.38.0 frozenlist-1.3.1 fsspec-2022.10.0 ftfy-6.1.1 funcy-1.17 future-0.18.2 gitdb-4.0.9 gitpython-3
.1.29 grandalf-0.6 idna-3.4 iniconfig-1.1.1 ipykernel-6.16.1 ipython-8.5.0 ipython-genutils-0.2.0 ipywidgets-8.0.2 jedi-0.18.1 jinja2-3.1.2 joblib-1.0.1
 jsonschema-4.16.0 jupyter-1.0.0 jupyter-client-7.4.3 jupyter-console-6.4.4 jupyter-contrib-core-0.4.0 jupyter-core-4.11.2 jupyter-highlight-selected-wo
rd-0.2.0 jupyter-latex-envs-1.4.6 jupyter-nbextensions-configurator-0.5.0 jupyter-server-1.21.0 jupyter_contrib_nbextensions-0.5.1 jupyterlab-pygments-0
.2.2 jupyterlab-widgets-3.0.3 kiwisolver-1.4.4 lxml-4.9.1 mailchecker-5.0.3 markupsafe-2.1.1 matplotlib-3.6.1 matplotlib-inline-0.1.6 mistune-2.0.4 mult
idict-6.0.2 nanotime-0.5.2 nbclassic-0.4.5 nbclient-0.7.0 nbconvert-7.2.2 nbformat-5.7.0 nest-asyncio-1.5.6 networkx-2.8.7 notebook-6.5.1 notebook-shim-
0.2.0 numpy-1.23.4 packaging-21.3 pandas-1.5.1 pandocfilters-1.5.0 parso-0.8.3 pathspec-0.9.0 phonenumbers-8.12.57 pickleshare-0.7.5 pillow-9.2.0 pluggy
10.1 pygments-2.13.0 pygtrie-2.5.0 pyparsing-3.0.9 pyrsistent-0.18.1 pytest-6.2.4 python-benedict-0.24.3 python-box-5.4.1 python-dateutil-2.8.2 python-f
sutil-0.7.0 python-slugify-6.1.2 pytz-2022.5 pywin32-304 pywinpty-2.0.8 pyyaml-5.4.1 pyzmq-24.0.1 qtconsole-5.3.2 qtpy-2.2.1 requests-2.28.1 rich-12.6.0
 ruamel.yaml-0.17.21 ruamel.yaml.clib-0.2.7 scikit-learn-0.24.2 scipy-1.9.3 shortuuid-1.0.9 shtab-1.5.5 six-1.16.0 smmap-5.0.0 sniffio-1.3.0 soupsieve-2
.3.2.post1 stack-data-0.5.1 tabulate-0.9.0 terminado-0.16.0 text-unidecode-1.3 threadpoolctl-3.1.0 tinycss2-1.2.1 toml-0.10.2 tornado-6.2 tqdm-4.64.1 tr
aitlets-5.5.0 typing-extensions-4.4.0 urllib3-1.26.12 voluptuous-0.13.1 wcwidth-0.2.5 webencodings-0.5.1 websocket-client-1.4.1 widgetsnbextension-4.0.3
 xmltodict-0.13.0 yarl-1.8.1 zc.lockfile-2.0
(dvc-venv) PS C:\Jan5-2021\DVC\course-ds-base>

**Comment by raviseerapu** [comment]
After i could deploy all required modules and trying to run the "[step-1-organize-ml-project.ipynb](http://localhost:8888/notebooks/notebooks/step-1-organize-ml-project.ipynb)" and it through the following message

import itertools

import joblib

import json

import matplotlib.pyplot as plt

import numpy as np

import pandas as pd

from sklearn.metrics import confusion_matrix, f1_score

from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_28656/688516382.py in <module>
      1 import itertools
----> 2 import joblib
      3 import json
      4 import matplotlib.pyplot as plt
      5 import numpy as np

ModuleNotFoundError: No module named 'joblib'


In-fact, i also checked respective joblib is exist in environment.

**Comment by Autodidact24** [comment]
Hi @raviseerapu,
Please share the output of the following from your Jupyter notebook:
`import sys
sys.executable`

I think you're notebook is not using `dvc-venv`. You might need to switch the kernel.

**Comment by vunguyen22271** [comment]
I use Python 3.11.6 on Mac:
```bash
joblib==1.2.0
matplotlib==3.9.0
numpy==1.23.5
pandas==2.2.2
pytest==6.2.4
python-box==5.4.1
pyyaml==6.0.1
scikit-learn==1.4.2
scipy==1.13.0
tqdm==4.63.1
dvc==3.50.2
dvc-s3==3.2.0
pygit2==1.14.1
```

Add these line before "from src..." in every files inside src/stages:
```python
import sys
sys.path.append('./')
```
and make sure you run comand in root repo dir
